bon_plan_client:
    resource: "@BonPlanClientBundle/Resources/config/routing.yml"
    prefix:   /client

bon_plan_admin:
    resource: "@BonPlanAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
